### ISSUE TITLE
Some elements not styled

### ISSUE THREAD

**Issue by skipster1337** [ZephyrCodesStuff/pywal-vencord#1]
Looks like discord updated something and the colors don't apply anymore for hovered/selected buttons and for the top bar in the friends list
![Screenshot from 2023-12-02 14-20-26](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/91155070/cfd9a8df-54fe-49a4-ad85-33d26c1ef84c)
![Screenshot from 2023-12-02 14-24-18](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/91155070/45bdf622-a169-4a87-9631-21206fb1fa04)

**Comment by ZephyrCodesStuff** [comment]
That's really weird, I've tried updating vencord to the latest possible version and I still can't replicate it. What are you using exactly? Vesktop or client?

**Comment by skipster1337** [comment]
I'm using the Discord desktop client from the Arch repos, with Vencord and OpenAsar installed using the vencord-cli installer that I got from the website.

**Comment by ZephyrCodesStuff** [comment]
I've tried downloading that and enabling a couple auto-generated themes I've made on the spot, but I still can't reproduce it. Can you please show me the info box on your version? I'd like to make sure we're both on the same builds.

![immagine](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/35661622/5a3ea29b-840b-479d-aae7-a3c628992cea)
![immagine](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/35661622/3b0d9a86-d343-40d3-bc7a-92baa96d2f2d)
![immagine](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/35661622/f2eaed3a-d008-401f-aa46-c91f0f4c8bc6)

**Comment by skipster1337** [comment]
![Screenshot from 2023-12-07 20-42-16](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/91155070/db0fa2e6-dca6-4011-ba38-86bc68ed04a1)
