### ISSUE TITLE
Unstyled Emoji Autocomplete

### ISSUE THREAD

**Issue by ghost** [ZephyrCodesStuff/pywal-vencord#4]
Hi, I noticed that when typing emojis, the autocomplete background color is set to default.

![image](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/76220359/5fdcecec-4a9b-4808-86f6-deb449b01cd1)

It seems like the background color is `var(--primary-630)`.

![image](https://github.com/ZephyrCodesStuff/pywal-vencord/assets/76220359/8ccf2521-61a0-4166-a4c2-65e77763eba2)

Great work on the theme!

**Comment by ZephyrCodesStuff** [comment]
I've added it to the theme and pushed it to the repo.

> Great work on the theme!

Thank you! 💙
