### ISSUE TITLE
member list background not styled

### ISSUE THREAD

**Issue by airwuu** [ZephyrCodesStuff/pywal-vencord#5]
love the pywal template! However, the right most side bar doesn't seem to be styled anymore.
![image](https://github.com/user-attachments/assets/f2deb47a-cdef-4475-9103-10d6f6b4f7fb)

**Comment by TheKamboy** [comment]
im also having the same issue

**Comment by ZephyrCodesStuff** [comment]
Thank you for the appreciation, @airwuu! Discord would appear to have either renamed the selectors or something similar.

I'll check and update the names in the template as soon as I have a moment, unless someone does it before I get to and PR's it.

**Comment by airwuu** [comment]
yeah i spent a bit of time and i found the missing selector. It works locally for me and i sent the PR :)
